services:
    Shopping\ApiDtoMapperBundle\Service\ArrayHelper: ~
    Shopping\ApiDtoMapperBundle\Service\StringHelper: ~

    Shopping\ApiDtoMapperBundle\EventListener\ControllerListener:
        tags:
            - {name: kernel.event_listener, event: kernel.controller}

    Shopping\ApiDtoMapperBundle\EventListener\SwaggerListener:
        tags:
            - {name: kernel.event_listener, event: kernel.controller}

    Shopping\ApiDtoMapperBundle\EventListener\MapperListener:
        autowire: true
        tags:
            - {name: kernel.event_listener, event: kernel.view, priority: 1000}

    Shopping\ApiDtoMapperBundle\Handler\PhpViewHandler: ~

    Shopping\ApiDtoMapperBundle\Describer\AnnotationDescriber:
        autowire: true
        public: false
        arguments:
            - '@nelmio_api_doc.routes.default'
            - '@nelmio_api_doc.controller_reflector'
        tags:
            - {name: 'nelmio_api_doc.route_describer', priority: -2000 }