services:
    Ofeige\Rfc1Bundle\Service\ArrayHelper: ~
    Ofeige\Rfc1Bundle\Service\StringHelper: ~

    Ofeige\Rfc1Bundle\EventListener\ControllerListener:
        tags:
            - {name: kernel.event_listener, event: kernel.controller}

    Ofeige\Rfc1Bundle\EventListener\SwaggerListener:
        tags:
            - {name: kernel.event_listener, event: kernel.controller}

    Ofeige\Rfc1Bundle\EventListener\MapperListener:
        autowire: true
        tags:
            - {name: kernel.event_listener, event: kernel.view, priority: 1000}

    Ofeige\Rfc1Bundle\Handler\PhpViewHandler: ~

    Ofeige\Rfc1Bundle\Describer\AnnotationDescriber:
        autowire: true
        public: false
        arguments:
            - '@nelmio_api_doc.routes.default'
            - '@nelmio_api_doc.controller_reflector'
        tags:
            - {name: 'nelmio_api_doc.route_describer', priority: -2000 }